### ISSUE TITLE
setting application_stack requires empty docker {} block

### ISSUE THREAD

**Issue by pniederlag** [telekom-mms/terraform-azurerm-app-service#14]
### Description

When adding a setting for application stak

```
application_stack = {
  node_version = 16
}
```

I ran into failures due to trying to access properties of docker, which is being null

workaround is to assign an empty docker{} block

```
application_stack = {
  node_version = 16
  docker = {
  }
}
```

### Reproduction steps

1. add an application stack like above

### Current Behavior

results in a failure

### Expected Behavior

only required settings must be provided

**Comment by mikaEz** [comment]
Issue is solved with new major version 2.0.0
